on: [push, pull_request]

jobs:
  clang:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [3.9, 4.0, 5.0, 6.0]
        arch: [x86, x86_64]
        buildType: [Debug, Release]
        page: [1, 2]
    steps:
      - uses: actions/checkout@v1
        with:
            fetch-depth: 1
      - name: install
        run: |
          chmod +x .ci/install.sh
          ./.ci/install.sh
      - name: run
        env:
            CONAN_CURRENT_PAGE: ${{matrix.page}}
            CONAN_TOTAL_PAGES: 2
            CONAN_BUILD_TYPES: ${{matrix.buildType}}
            CONAN_ARCHS: ${{matrix.arch}}
            CONAN_CLANG_VERSIONS: ${{matrix.version}}
            CONAN_OPTIONS: "harfbuzz:with_glib=False,qt:qtdeclarative=True,qt:qtmultimedia=True,qt:qttools=True,qt:qttranslations=True,qt:qtdoc=True,qt:qtrepotools=True,qt:qtqa=True,qt:qtquickcontrols2=True"
            CONAN_USE_DOCKER: 1
        run: |
          chmod +x .ci/run.sh
          ./.ci/run.sh